### ISSUE TITLE
inconsistently cased taxonID prefixes: [Acari_10682343] and [acari_10766101] 

### ISSUE THREAD

**Issue by jhpoelen** [njdowdy/tpt-taxonomy#16]
inconsistently cased taxonID prefixes: [Acari_10682343] and [acari_10766101] 

in first three lines of Acari-standarized-v2.csv, I found:

source | taxonID
-- | --
TPT | acari_6995
GBIF | Acari_10682343
GBIF | acari_10766101

where second and third record use inconsistent prefixes. 

Is this intended behavior?

**Comment by EMTuckerLab** [comment]
No... I'm not sure why some are capitalized and others aren't. Ideally they
should be consistent. Probably capitalized, but I don't know that it
matters for the ID... I can fix and upload a new file tomorrow.

----------
Erika Tucker, PhD (s*he/her/hers*)
Milwaukee Public Museum | TPT  <https://parasitetracker.org/>Taxonomy
<https://parasitetracker.org/>Digitization Manager
<https://parasitetracker.org/>
Biodiversity Outreach Network (BON) <https://www.bon-earth.org/> | Research
Associate <https://www.bon-earth.org/about-us> | S2 Administrative Manager
<https://www.bon-earth.org/_files/ugd/68d22d_372c2df8960041a1a5328b5e43c7b3c3.pdf>
*Entomologist, Museum Specialist, & Researcher*
ORCiD 0000-0002-8822-2315 <https://orcid.org/0000-0002-8822-2315>

Check it out!
   *Bug.News <http://bug.news/> *(blog)
   TPT Resource Hub <https://bit.ly/TPTresourceHub> (taxonomy)
   GloBI How-To <https://www.globalbioticinteractions.org/how-to> (help
page)
   Entomological Resources <https://www.bon-earth.org/products-resources>
(supplies, DIY, etc.)
   BugFlow <https://entcollnet.github.io/BugFlow/> (digitization workflows)
   *Brood X & Spotted Lanternfly Jewelry*
<https://www.earthengypsydesigns.com/category/bugs>!

<https://www.earthengypsydesigns.com/product/17yr-cicada-wings-fw-necklace-stones>
<https://www.earthengypsydesigns.com/product/17yr-cicada-wings-h2>
<https://www.earthengypsydesigns.com/product/spotted-lanternfly-framed-teardrop-hw>
<https://www.earthengypsydesigns.com/product/spotted-lanternfly-earrings-fw-pearl>

**Comment by jhpoelen** [comment]
@EMTuckerLab as far as I can tell, this Acari vs. acari issue has not been fixed. Would you like me to fix it for you?

**Comment by jhpoelen** [comment]
I've included a fix for this prefix issue in pull request https://github.com/njdowdy/tpt-taxonomy/pull/20

**Comment by EMTuckerLab** [comment]
Thanks @jhpoelen. Sorry, I meant to fix it and then got caught up in something else. Posted a question in #20 about the fixes before merging the branch...

**Comment by jhpoelen** [comment]
resolved via https://github.com/njdowdy/tpt-taxonomy/pull/20 .
