### ISSUE TITLE
suggest to generate new release

### ISSUE THREAD

**Issue by jhpoelen** [njdowdy/tpt-taxonomy#19]
Many improvements have been made since v1.0.3 was released in October 2021. 

Suggest to prepare a new TPT Taxonomy publication for release.

**Comment by jhpoelen** [comment]
Current release:

Dr. Nicolas J. Dowdy, Dr. Vijay Barve, Teresa Mayfield-Meyer, Kathryn Sullivan, & Dr. Jennifer M. Zaspel. (2021). njdowdy/tpt-taxonomy: TPT Taxonomic Resource v1.0.3 (v1.0.3) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5562742

**Comment by jhpoelen** [comment]
oh, by the way . . . happy anniversary v1.0.3 TPT Taxonomy . . . it's been exactly one years since 1.0.3 was released. 

:partying_face:

**Comment by EMTuckerLab** [comment]
I would second the vote for an updated/new release :)

**Comment by njdowdy** [comment]
Done! Happy birthday, TPT Taxonomy!

[https://zenodo.org/record/7215550#.Y01X4n7MLUJ](https://zenodo.org/record/7215550#.Y01X4n7MLUJ)

**Comment by jhpoelen** [comment]
@njdowdy thanks!

I've updates citation and references in Poelen, Jorrit H. (2022). Nomer Corpus of Taxonomic Resources hash://sha256/b3742bf43d9da0a8ed5522659199f47d68d31aaf46c90381190f324c1ac143f2 hash://md5/26a9b6c796567b3985e8bfe750ea2341 (0.7) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7196029 .

See attached screenshots. Please let me know if I missed anything.

![Screenshot from 2022-10-17 08-28-29](https://user-images.githubusercontent.com/1084872/196189733-22dcfdc5-303b-4875-89ae-9cf5246547f9.png)
![Screenshot from 2022-10-17 08-28-19](https://user-images.githubusercontent.com/1084872/196189735-aae98a6f-4e1b-4fbf-9e00-a5d7b1d63439.png)
![Screenshot from 2022-10-17 08-28-07](https://user-images.githubusercontent.com/1084872/196189737-584121a5-0e62-4cec-bde3-3d3cbf70439d.png)

**Comment by njdowdy** [comment]
@jhpoelen, it looks good to me. Bookmarked! 😁
