### ISSUE TITLE
suggest to use unix style newlines ("\n") instead of MSDOS ("\r\n") 

### ISSUE THREAD

**Issue by jhpoelen** [njdowdy/tpt-taxonomy#2]
the *_standardized.csv appear to be using MSDOS line endings ("\r\n"). 

Suggest to use unix style newlines ("\n") instead.

see https://support.nesi.org.nz/hc/en-gb/articles/218032857-Converting-from-Windows-style-to-UNIX-style-line-endings or search around for ways to make sure that these "\r" characters don't enter the data sheets.

**Comment by jhpoelen** [comment]
related to https://github.com/globalbioticinteractions/globalbioticinteractions/issues/694

**Comment by EMTuckerLabUMMZ** [comment]
I'll work on fixing this... I had someone help me look at the line style endings and they actually appear to be fine according to terminal... I also ran the commands in the link @jhpoelen  sent - thank you. It didn't actually change the *_standardized files, although it was happy to modify the original .csv files. It does look like my super old mac excel software did weird things to the file encoding itself though (mix of ASCII, UTF, ISO, non-ISO, etc.). I'll try and get fixed versions up asap so you can test them.

**Comment by EMTuckerLabUMMZ** [comment]
Oks... I think I fixed the ending and file encoding thing (with a lot of help) for all but the siphonaptera-standardized.csv (looks like @njdowdy modified it and I didn't want to mess up anything in the newer file). See here: https://github.com/njdowdy/tpt-taxonomy/pull/8 . Let me know if this fixes the issues...

**Comment by njdowdy** [comment]
Yeah, I discovered an easy to fix error in the file so I fixed it. It was unrelated to this issue though. But it may have possible killed two birds with one stone unintentionally?

**Comment by EMTuckerLabUMMZ** [comment]
I believe all files should be have the endings fixed now... I uploaded the last file on Friday, just forgot to add it to the issues log..

**Comment by jhpoelen** [comment]
resolved via #8
