### ISSUE TITLE
Aves/Mammalia do not have standardized tables

### ISSUE THREAD

**Issue by jhpoelen** [njdowdy/tpt-taxonomy#4]
@EMTuckerLabUMMZ Thanks for standardizing the parasite name tables.

I noticed that Aves and Mammalia names are not yet have a similar schema. Is this expected?

**Comment by jhpoelen** [comment]
related to https://github.com/globalbioticinteractions/globalbioticinteractions/issues/694

**Comment by EMTuckerLabUMMZ** [comment]
@jhpoelen I'm working on the Aves and Mammalia now... I should have Aves finished this week and hopefully Mammalia next week

**Comment by jhpoelen** [comment]
@EMTuckerLabUMMZ Ok, thanks for letting me know. Just wanted to make sure I wasn't missing anything.
