### ISSUE TITLE
question: are there synonyms beyond the Acari name list? 

### ISSUE THREAD

**Issue by jhpoelen** [njdowdy/tpt-taxonomy#7]

**Comment by jhpoelen** [comment]
related to https://github.com/globalbioticinteractions/globalbioticinteractions/issues/694

**Comment by njdowdy** [comment]
Could you clarify this question? Do you mean "do synonyms exist in other name lists", "do Acari synonyms exist beyond the Acari name list", or something else?

If the former - there are synonyms contained in the Phthiraptera and Siphonaptera datasets for example. If the latter - there are also names on GBIF that do not exist in these resources. If something else, please elaborate and I will try to answer.

**Comment by jhpoelen** [comment]
@njdowdy thanks for responding.

I meant to ask:

Do the TPT provided name lists contain synonyms beyond those in the TPT Acari name list? 

I just wanted to confirm my observation that only TPT Acari names contained definitions of synonyms. Please let me know if this clarifies my question.

**Comment by njdowdy** [comment]
Ah, then yes - there are synonyms contained in the Phthiraptera and Siphonaptera datasets. 

In the case of the Phthiraptera dataset they are stored in a perhaps unorthodox way, following the taxotools output pipeline. Essentially, the "accid" acts as a foreign key to the "accepted name". A little bit more work would need to be done to generate an "acceptedName" field for example. But the information is there.

**Comment by jhpoelen** [comment]
@njdowdy thanks for sharing that synonyms exist in the Phthiraptera and Siphonaptera datasets.

**Comment by njdowdy** [comment]
@jhpoelen sure! Sorry that wasn't more obvious.
